# Data Cleaning

## Objective

Prepare the dataset for exploratory data analysis by correcting data quality issues while preserving data integrity.

### Tasks

- Correct incorrect data types
- Validate missing values
- Verify duplicate records
- Assess redundant columns
- Export a cleaned dataset

In [3]:
import pandas as pd
import numpy as np

In [4]:
df =pd.read_excel("/Users/ashwathimd/DataLab/Projects/customer-churn-analysis/data/raw/telco_customer_churn_raw.xlsx")

In [5]:
df.dtypes

CustomerID               str
Count                  int64
Country                  str
State                    str
City                     str
Zip Code               int64
Lat Long                 str
Latitude             float64
Longitude            float64
Gender                   str
Senior Citizen           str
Partner                  str
Dependents               str
Tenure Months          int64
Phone Service            str
Multiple Lines           str
Internet Service         str
Online Security          str
Online Backup            str
Device Protection        str
Tech Support             str
Streaming TV             str
Streaming Movies         str
Contract                 str
Paperless Billing        str
Payment Method           str
Monthly Charges      float64
Total Charges         object
Churn Label              str
Churn Value            int64
Churn Score            int64
CLTV                   int64
Churn Reason             str
dtype: object

In [6]:
df["Total Charges"].head()

0     108.15
1     151.65
2      820.5
3    3046.05
4     5036.3
Name: Total Charges, dtype: object

In [7]:
df["Total Charges"].tail()

7038    1419.4
7039    1990.5
7040    7362.9
7041    346.45
7042    6844.5
Name: Total Charges, dtype: object

In [8]:
df["Total Charges"].sample(10, random_state=42)

185     1269.55
2715    1074.65
3825       40.9
1807     519.15
132     4131.95
1263     829.55
3732     171.45
1672    1574.45
811        25.1
2526      504.2
Name: Total Charges, dtype: object

In [9]:
df["Total Charges"].apply(type).value_counts()

Total Charges
<class 'float'>    6708
<class 'int'>       324
<class 'str'>        11
Name: count, dtype: int64

In [10]:
df[df["Total Charges"].str.strip() == ""]

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
2234,4472-LVYGI,1,United States,California,San Bernardino,92408,"34.084909, -117.258107",34.084909,-117.258107,Female,...,Two year,Yes,Bank transfer (automatic),52.55,,No,0,36,2578,NaN
2438,3115-CZMZD,1,United States,California,Independence,93526,"36.869584, -118.189241",36.869584,-118.189241,Male,...,Two year,No,Mailed check,20.25,,No,0,68,5504,NaN
2568,5709-LVOEQ,1,United States,California,San Mateo,94401,"37.590421, -122.306467",37.590421,-122.306467,Female,...,Two year,No,Mailed check,80.85,,No,0,45,2048,NaN
2667,4367-NUYAO,1,United States,California,Cupertino,95014,"37.306612, -122.080621",37.306612,-122.080621,Male,...,Two year,No,Mailed check,25.75,,No,0,48,4950,NaN
2856,1371-DWPAZ,1,United States,California,Redcrest,95569,"40.363446, -123.835041",40.363446,-123.835041,Female,...,Two year,No,Credit card (automatic),56.05,,No,0,30,4740,NaN
4331,7644-OMVMY,1,United States,California,Los Angeles,90029,"34.089953, -118.294824",34.089953,-118.294824,Male,...,Two year,No,Mailed check,19.85,,No,0,53,2019,NaN
4687,3213-VVOLG,1,United States,California,Sun City,92585,"33.739412, -117.173334",33.739412,-117.173334,Male,...,Two year,No,Mailed check,25.35,,No,0,49,2299,NaN
5104,2520-SGTTA,1,United States,California,Ben Lomond,95005,"37.078873, -122.090386",37.078873,-122.090386,Female,...,Two year,No,Mailed check,20.00,,No,0,27,3763,NaN
5719,2923-ARZLG,1,United States,California,La Verne,91750,"34.144703, -117.770299",34.144703,-117.770299,Male,...,One year,Yes,Mailed check,19.70,,No,0,69,4890,NaN
6772,4075-WKNIU,1,United States,California,Bell,90201,"33.970343, -118.171368",33.970343,-118.171368,Female,...,Two year,No,Mailed check,73.35,,No,0,44,2342,NaN
6840,2775-SEFEE,1,United States,California,Wilmington,90744,"33.782068, -118.262263",33.782068,-118.262263,Male,...,Two year,Yes,Bank transfer (automatic),61.90,,No,0,65,5188,NaN

In [13]:
df[df["Total Charges"].str.strip() == ""][
   [ "CustomerID", "Tenure Months" , "Monthly Charges", "Contract", "Churn Label" ]
]

      CustomerID  Tenure Months  Monthly Charges  Contract Churn Label
2234  4472-LVYGI              0            52.55  Two year          No
2438  3115-CZMZD              0            20.25  Two year          No
2568  5709-LVOEQ              0            80.85  Two year          No
2667  4367-NUYAO              0            25.75  Two year          No
2856  1371-DWPAZ              0            56.05  Two year          No
4331  7644-OMVMY              0            19.85  Two year          No
4687  3213-VVOLG              0            25.35  Two year          No
5104  2520-SGTTA              0            20.00  Two year          No
5719  2923-ARZLG              0            19.70  One year          No
6772  4075-WKNIU              0            73.35  Two year          No
6840  2775-SEFEE              0            61.90  Two year          No

In [14]:
df["Total Charges"] = pd.to_numeric(
    df["Total Charges"],
    errors = "coerce"
)

In [15]:
df["Total Charges"].dtype

dtype('float64')

In [16]:
df["Total Charges"].isna().sum()

np.int64(11)

### Total Charges

- Converted `Total Charges` from `object` to `float64`.
- Blank values were converted to `NaN`.
- These correspond to customers with zero tenure and are considered valid missing values.
- No imputation was performed.

In [17]:
df.nunique().sort_values()

Count                   1
Country                 1
State                   1
Senior Citizen          2
Churn Value             2
Churn Label             2
Paperless Billing       2
Gender                  2
Partner                 2
Dependents              2
Phone Service           2
Online Backup           3
Online Security         3
Streaming TV            3
Multiple Lines          3
Internet Service        3
Device Protection       3
Contract                3
Streaming Movies        3
Tech Support            3
Payment Method          4
Churn Reason           20
Tenure Months          73
Churn Score            85
City                 1129
Monthly Charges      1585
Longitude            1651
Latitude             1652
Lat Long             1652
Zip Code             1652
CLTV                 3438
Total Charges        6530
CustomerID           7043
dtype: int64

In [18]:
df_clean = df.drop(
    columns=[
        "Count",
        "Country",
        "State",
        "Lat Long"
    ]
)

In [19]:
df_clean.shape

(7043, 29)

In [20]:
df_clean.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   str
 1   City               7043 non-null   str
 2   Zip Code           7043 non-null   int64
 3   Latitude           7043 non-null   float64
 4   Longitude          7043 non-null   float64
 5   Gender             7043 non-null   str
 6   Senior Citizen     7043 non-null   str
 7   Partner            7043 non-null   str
 8   Dependents         7043 non-null   str
 9   Tenure Months      7043 non-null   int64
 10  Phone Service      7043 non-null   str
 11  Multiple Lines     7043 non-null   str
 12  Internet Service   7043 non-null   str
 13  Online Security    7043 non-null   str
 14  Online Backup      7043 non-null   str
 15  Device Protection  7043 non-null   str
 16  Tech Support       7043 non-null   str
 17  Streaming TV       7043 non-null   str
 18  Streaming Movies   7043 non-null   str
 19  Contract           7043 non-null   str
 20  Paperless Billing  7043 non-null   str
 21  Payment Method     7043 non-null   str
 22  Monthly Charges    7043 non-null   float64
 23  Total Charges      7032 non-null   float64
 24  Churn Label        7043 non-null   str
 25  Churn Value        7043 non-null   int64
 26  Churn Score        7043 non-null   int64
 27  CLTV               7043 non-null   int64
 28  Churn Reason       1869 non-null   str
dtypes: float64(4), int64(5), str(20)
memory usage: 1.6 MB

## Data Cleaning Summary

### Cleaning Performed

- Converted `Total Charges` from `object` to `float64`.
- Converted blank strings in `Total Charges` to `NaN`.
- Retained the missing values, as they represent customers with zero tenure.
- Removed redundant columns:
  - `Count`
  - `Country`
  - `State`
  - `Lat Long`

### Dataset Status

- Duplicate records: None
- Remaining missing values:
- `Total Charges` (11 valid missing values)
- `Churn Reason` (expected for non-churned customers)

## Data Integrity Validation

- Dataset dimensions were preserved after cleaning.
- No customer records were removed.
- Only valid business-related missing values remain.
- The dataset is consistent and ready for exploratory analysis.

The dataset is now ready for Exploratory Data Analysis (EDA).

In [23]:
df_clean.to_excel(
    "/Users/ashwathimd/DataLab/Projects/customer-churn-analysis/data/processed/telco_customer_churn_clean.xlsx",
    index=False
)